// Generated from https://www.angelspizza.com.ph/locations API
// Source endpoints: /api/province-branches-for-location-page?page=1..3
export const ANGEL_PIZZA_STORES = [
  { id: "1", name: "Butuan", name_en: "Butuan", name_zh: "Butuan", region: "Agusan Del Norte", address: "Gf Units 7A-10A, Equina Dos Bldg., Cor. Doongan Road, J.C. Aquino Ave. Bayanihan Pob. City of Butuan Agusan Del Norte", phone: "" },
  { id: "2", name: "Baguio Palace Hotel", name_en: "Baguio Palace Hotel", name_zh: "Baguio Palace Hotel", region: "Baguio", address: "Gf - Unit A Baguio Palace Hotel 21 Legarda Road Legarda-Burnham-Kisad Baguio City Benguet", phone: "" },
  { id: "3", name: "Balanga Bataan", name_en: "Balanga Bataan", name_zh: "Balanga Bataan", region: "Bataan", address: "CAPITOL SQUARE CORNER QUEZON STREET SAN JOSE CITY OF BALANGA CAPITAL BATAAN", phone: "" },
  { id: "4", name: "Lipa Batangas", name_en: "Lipa Batangas", name_zh: "Lipa Batangas", region: "Batangas", address: "Gen Luna Street Sabang Lipa City Batangas", phone: "(043)727-5127" },
  { id: "5", name: "Lemery Batangas", name_en: "Lemery Batangas", name_zh: "Lemery Batangas", region: "Batangas", address: "4209 BARREDO BUILDING ILUSTRE AVE., PALANAS LEMERY BATANGAS", phone: "" },
  { id: "6", name: "Outlets", name_en: "Outlets", name_zh: "Outlets", region: "Batangas", address: "Unit R01 & R02 The Outlet at Lipa Main BLVD Lima Technology Center San Lucas City of Lipa Batangas", phone: "" },
  { id: "7", name: "Malolos", name_en: "Malolos", name_zh: "Malolos", region: "Bulacan", address: "G/F MCF Lifestyle Hub, McArthur Highway, Brgy. Tikay, Malolos, Bulacan", phone: "(044)-812-3333 | 0915-351-4289 | 0935-159-6258 | 0968-250-2252" },
  { id: "8", name: "Sta. Maria Bulacan", name_en: "Sta. Maria Bulacan", name_zh: "Sta. Maria Bulacan", region: "Bulacan", address: "Unit-1 Gateway Building 54 Gov. Halili Highway Bagbaguin Sta. Maria Bulacan", phone: "(044)816-3761" },
  { id: "9", name: "Waltermart Baliuag Bulacan", name_en: "Waltermart Baliuag Bulacan", name_zh: "Waltermart Baliuag Bulacan", region: "Bulacan", address: "Waltermart Sabang Baliuag Bulacan", phone: "" },
  { id: "10", name: "Sapang Palay SJDM Bulacan", name_en: "Sapang Palay SJDM Bulacan", name_zh: "Sapang Palay SJDM Bulacan", region: "Bulacan", address: "M Community Mall SJDMC Area D Santa Cruz City of San Jose Del Monte Bulacan", phone: "" },
  { id: "11", name: "Marilao Bulacan", name_en: "Marilao Bulacan", name_zh: "Marilao Bulacan", region: "Bulacan", address: "G/F Unit 1&2 Go Land Dev't Enterprises Inc. Villarica Road Santa Rosa l Marilao Bulacan", phone: "" },
  { id: "12", name: "San Miguel Bulacan", name_en: "San Miguel Bulacan", name_zh: "San Miguel Bulacan", region: "Bulacan", address: "ECG Commercial Complex, National Rd, San Miguel, 3011 Bulacan", phone: "" },
  { id: "13", name: "Meycuayan", name_en: "Meycuayan", name_zh: "Meycuayan", region: "Bulacan", address: "Mary Mount Hospital, C.P. Soriente Building Camalig City of Meycauayan Bulacan", phone: "" },
  { id: "14", name: "Xentromall", name_en: "Xentromall", name_zh: "Xentromall", region: "Bulacan", address: "Xentro Mall Bulihan City of Malolos Bulacan", phone: "" },
  { id: "15", name: "Balzain West Tuguegarao", name_en: "Balzain West Tuguegarao", name_zh: "Balzain West Tuguegarao", region: "Cagayan", address: "Tuddao Bldg., Balzain Highway, Balzain West, West, Centro 12, Tuguegarao City Cagayan", phone: "" },
  { id: "16", name: "Imus Cavite", name_en: "Imus Cavite", name_zh: "Imus Cavite", region: "Cavite", address: "Sonrise Building, Gen. Emilio Aguinaldo Highway Tanzang Luma Imus City Cavite", phone: "472-2222" },
  { id: "17", name: "Bacoor Cavite", name_en: "Bacoor Cavite", name_zh: "Bacoor Cavite", region: "Cavite", address: "G-12A Molino Road RFC Molino Mall Molino II Bacoor City", phone: "(46)853-8846" },
  { id: "18", name: "General Trias Cavite", name_en: "General Trias Cavite", name_zh: "General Trias Cavite", region: "Cavite", address: "(Near Gen Star Commercial) Manggahan 4107 General Trias Cavite", phone: "(046) 8906606" },
  { id: "19", name: "Dasmarinas Cavite", name_en: "Dasmarinas Cavite", name_zh: "Dasmarinas Cavite", region: "Cavite", address: "Aguinaldo Hiway Zone IV Pob. City of Dasmarinas Cavite", phone: "(046) 8855-984" },
  { id: "20", name: "Silang Village Cavite", name_en: "Silang Village Cavite", name_zh: "Silang Village Cavite", region: "Cavite", address: "Unit F3-5 Aguinaldo Highway San Vicente II Silang Cavite", phone: "0927-227-5758" },
  { id: "21", name: "Midtown Silang Cavite", name_en: "Midtown Silang Cavite", name_zh: "Midtown Silang Cavite", region: "Cavite", address: "141 Midtown Square Governors Drive Bulihan Silang Cavite", phone: "" },
  { id: "22", name: "Poblacion Rosario Cavite", name_en: "Poblacion Rosario Cavite", name_zh: "Poblacion Rosario Cavite", region: "Cavite", address: "21 MARSEILA ST POBLACION ROSARIO CAVITE", phone: "" },
  { id: "23", name: "Talaba", name_en: "Talaba", name_zh: "Talaba", region: "Cavite", address: "Unit 101 Ground Floor Mayon-Gcc Plaza Aguinaldo Highway Talaba VII City of Bacoor Cavite", phone: "" },
  { id: "24", name: "Tagaytay", name_en: "Tagaytay", name_zh: "Tagaytay", region: "Cavite", address: "TSL 9089 Gen. Emilio Aguinaldo Hi-Way Mendez Crossing East City of Tagaytay Cavite", phone: "" },
  { id: "25", name: "Paliparan III", name_en: "Paliparan III", name_zh: "Paliparan III", region: "Cavite", address: "Molino - Paliparan Rd, Dasmariñas, Cavite", phone: "0927-519-7588" },
  { id: "26", name: "ANABU II", name_en: "ANABU II", name_zh: "ANABU II", region: "Cavite", address: "JDC Building, Anabu II, A Aguinaldo Hwy, Imus, Cavite", phone: "0954-443-2244" },
  { id: "27", name: "Banilad", name_en: "Banilad", name_zh: "Banilad", region: "Cebu", address: "G/F GQS Plaza, Gov. M. Cuenco Ave., Banilad, Cebu (beside UC Banilad)", phone: "0995-835-8222" },
  { id: "28", name: "Mactan", name_en: "Mactan", name_zh: "Mactan", region: "Cebu", address: "Mactan Town Center, Brgy. Basak, Lapu-Lapu City, Cebu", phone: "231-8555 | 0915-024-4977" },
  { id: "29", name: "Basak Mandaue Cebu", name_en: "Basak Mandaue Cebu", name_zh: "Basak Mandaue Cebu", region: "Cebu", address: "530 Cebu N Rd, Mandaue City, Cebu", phone: "" },
  { id: "30", name: "Lapu-lapu Cebu", name_en: "Lapu-lapu Cebu", name_zh: "Lapu-lapu Cebu", region: "Cebu", address: "UNIT CT 128-129 LG GARDEN WALK BLDG. 2 MACTAN LAPU-LAPU CITY OPON CEBU", phone: "" },
  { id: "31", name: "Gaisano Capitol Danao Cebu", name_en: "Gaisano Capitol Danao Cebu", name_zh: "Gaisano Capitol Danao Cebu", region: "Cebu", address: "Ground Floor Gaisano Capital F. Ralota St. Poblacion Danao City Cebu", phone: "032-5031729" },
  { id: "32", name: "Consolacion Cebu", name_en: "Consolacion Cebu", name_zh: "Consolacion Cebu", region: "Cebu", address: "National Road Pitogo Consolacion Cebu", phone: "" },
  { id: "33", name: "IT Park", name_en: "IT Park", name_zh: "IT Park", region: "Cebu", address: "Ground Floor Unit 9 Calyx Centre Cebu IT Park Apas City of Cebu Cebu", phone: "" },
  { id: "34", name: "Avida Davao", name_en: "Avida Davao", name_zh: "Avida Davao", region: "Davao", address: "Unit 5,6,7 Avida Tower C.M. Recto Barangay 34-D POB. Poblacion District Davao City Davao Del Sur", phone: "" },
  { id: "35", name: "Tagum", name_en: "Tagum", name_zh: "Tagum", region: "Davao", address: "Lapu-Lapu Street, Tagum, Davao Del Norte, Davao", phone: "" },
  { id: "36", name: "Paco Roman, Laoag", name_en: "Paco Roman, Laoag", name_zh: "Paco Roman, Laoag", region: "Ilocos Norte", address: "Ground Floor Vmjj Paco Roman St Bgy. No. 11, Santa Balbina Pob. Laoag City Capital Ilocos Norte", phone: "" },
  { id: "37", name: "Santiago", name_en: "Santiago", name_zh: "Santiago", region: "Isabela", address: "Ground Floor SKPC Building National Highway Villasis City of Santiago Isabela", phone: "" },
  { id: "38", name: "Citiplace BLDG San Fernando", name_en: "Citiplace BLDG San Fernando", name_zh: "Citiplace BLDG San Fernando", region: "La Union", address: "Citiplace Quezon Avenue Barangay Iii Pob. City Of San Fernando Capital La Union", phone: "" },
  { id: "39", name: "Agoo", name_en: "Agoo", name_zh: "Agoo", region: "La Union", address: "Ground Floor Catena Lev Building Mc Arthur Highway San Miguel Agoo La Union", phone: "" },
  { id: "40", name: "Sta. Rosa", name_en: "Sta. Rosa", name_zh: "Sta. Rosa", region: "Laguna", address: "Unit 3&4 Diamond St., Balibago Complex, Sta. Rosa, Laguna", phone: "(049)-502-2222 | 0963-784-7566 | 0967-844-9215" },
  { id: "41", name: "Calamba", name_en: "Calamba", name_zh: "Calamba", region: "Laguna", address: "Julita Building 3, Sampaguita corner Chipeco Avenue Extension Halang Calamba City Laguna", phone: "(049)559-8679" },
  { id: "42", name: "San Pedro Laguna", name_en: "San Pedro Laguna", name_zh: "San Pedro Laguna", region: "Laguna", address: "359 NATIONAL HIGHWAY NUEVA SAN PEDRO LAGUNA", phone: "(02)8922-2222" },
  { id: "43", name: "San Pablo Laguna", name_en: "San Pablo Laguna", name_zh: "San Pablo Laguna", region: "Laguna", address: "KM.83 BLK 4 LOT 4 Maharlika Medex San Francisco San Pablo City Laguna", phone: "" },
  { id: "44", name: "Sta Cruz Laguna", name_en: "Sta Cruz Laguna", name_zh: "Sta Cruz Laguna", region: "Laguna", address: "Lot 17 block10, Capitol Ville, EFC BLDG Brgy. Gatid, Sta. Cruz, Laguna", phone: "0967-167-0091" },
  { id: "45", name: "Biñan", name_en: "Biñan", name_zh: "Biñan", region: "Laguna", address: "A. Bonifacio St. cor Padre Jose Ma. Burgos St., Brgy Santo Doningo, Biñan City, Laguna", phone: "" },
  { id: "46", name: "Cabuyao", name_en: "Cabuyao", name_zh: "Cabuyao", region: "Laguna", address: "110 Comercio Centrale Brgy. Pulo Cabuyao, Laguna", phone: "0966-223-7145" },
  { id: "47", name: "Bel-Air Laguna", name_en: "Bel-Air Laguna", name_zh: "Bel-Air Laguna", region: "Laguna", address: "Laluz Building Phase 5 Lot 5-B Sta.Rosa-Tagaytay Road Laguna Bel Air 2 Don Jose City of Santa Rosa Laguna", phone: "" },
  { id: "48", name: "Gil Fernando Marikina", name_en: "Gil Fernando Marikina", name_zh: "Gil Fernando Marikina", region: "Metro Manila", address: "Unit 6 Thaddeus Arcade Pitpitan St. Corner Gil Fernando Avenue Marikina City", phone: "8922-2222 | 7358-4471 | 8722-1620" },
  { id: "49", name: "Mandaluyong", name_en: "Mandaluyong", name_zh: "Mandaluyong", region: "Metro Manila", address: "33 Mayon St, Mandaluyong, Metro Manila", phone: "(02) 8922 2222" },
  { id: "50", name: "C. Raymundo Ave. Pasig", name_en: "C. Raymundo Ave. Pasig", name_zh: "C. Raymundo Ave. Pasig", region: "Metro Manila", address: "Unit G104 C. Raymundo Avenue Maybunga Pasig City Metro Manila", phone: "8922-2222 | 8569-8789" },
  { id: "51", name: "Bel-Air Makati", name_en: "Bel-Air Makati", name_zh: "Bel-Air Makati", region: "Metro Manila", address: "#1 Constellation St., Bel-air Makati Ave., Makati City", phone: "8922-2222 | 8895-8888 | 8801-8878" },
  { id: "52", name: "Commonwealth Ave QC", name_en: "Commonwealth Ave QC", name_zh: "Commonwealth Ave QC", region: "Metro Manila", address: "#103-G Commonwealth Ave. Fairview Quezon City", phone: "8922-2222 | 8461-7501 | 8461-7502" },
  { id: "53", name: "Malate", name_en: "Malate", name_zh: "Malate", region: "Metro Manila", address: "888 Gateway Plaza 2126 A.Mabini St. Malate, Manila", phone: "8922-2222 | 8852-1935 | 8353-5989" },
  { id: "54", name: "President's Ave Sucat", name_en: "President's Ave Sucat", name_zh: "President's Ave Sucat", region: "Metro Manila", address: "L21 B4 Rd. Lot 1 President Ave. Theoville Vill. San Dionisio Parañaque City", phone: "8922-2222 | 8788-0011" },
  { id: "55", name: "San Sebastian Quiapo", name_en: "San Sebastian Quiapo", name_zh: "San Sebastian Quiapo", region: "Metro Manila", address: "Ultima Bldg San Rafael Street Quiapo Manila City", phone: "8922-2222 | 8733-4946 | 8252-3736" },
  { id: "56", name: "Kalayaan Ave. QC", name_en: "Kalayaan Ave. QC", name_zh: "Kalayaan Ave. QC", region: "Metro Manila", address: "#47 Puno Bldg. Kalayaan Ave. Quezon City", phone: "8922-2222 | 7729-6558" },
  { id: "57", name: "Las Piñas", name_en: "Las Piñas", name_zh: "Las Piñas", region: "Metro Manila", address: "Alabang-Zapote Road, Pamplona Tres Las Piñas City (beside Maybank) Las Piñas City Metro Manila 1554", phone: "(02)89222222" },
  { id: "58", name: "Retiro QC", name_en: "Retiro QC", name_zh: "Retiro QC", region: "Metro Manila", address: "D. Tuazon, Santa Mesa Heights, Quezon City, Metro Manila", phone: "(02)89222222" },
  { id: "59", name: "Monumento", name_en: "Monumento", name_zh: "Monumento", region: "Metro Manila", address: "Lot 14 Blk 1 #75 Mc Arthur Hi-way Caloocan City", phone: "8922-2222 | 8277-7869" },
  { id: "60", name: "Valenzuela", name_en: "Valenzuela", name_zh: "Valenzuela", region: "Metro Manila", address: "Prime One Bldg., G. Lazaro St., Brgy. Dalandanan Valenzuela City", phone: "(02)8712-5862" },
  { id: "61", name: "Quirino Highway Novaliches", name_en: "Quirino Highway Novaliches", name_zh: "Quirino Highway Novaliches", region: "Metro Manila", address: "672 Quirino Highway, Brgy. Bagbag, Novaliches, Quezon City", phone: "0968-229-0303 | 0917-978-6802 | (02) 8536-5926" },
  { id: "62", name: "Metroplaza North Caloocan", name_en: "Metroplaza North Caloocan", name_zh: "Metroplaza North Caloocan", region: "Metro Manila", address: "Neonprint, Unit 2F-T17, 2nd Floor Metroplaza Mall, Quirino Hiway cor, Malaria Rd, North, Caloocan", phone: "8922-2222 | (02) 8531-3517 | 0916-723-5594" },
  { id: "63", name: "Pateros", name_en: "Pateros", name_zh: "Pateros", region: "Metro Manila", address: "#120 M. Almeda st., San Roque, Pateros, City, Pateros City, 4103 Metro Manila", phone: "(02)8772-7811" },
  { id: "64", name: "Petron EDSA Makati", name_en: "Petron EDSA Makati", name_zh: "Petron EDSA Makati", region: "Metro Manila", address: "Edsa Cor. Antonio Arnaiz Avenue Dasmarinas City of Makati NCR, Fourth District", phone: "(02)8922-2222" },
  { id: "65", name: "Northridge Congressional QC", name_en: "Northridge Congressional QC", name_zh: "Northridge Congressional QC", region: "Metro Manila", address: "12 Congressional Ave Bahay Toro Quezon City - 00002 NCR, Second District", phone: "(02)8922-2222 | (02) 8731-9242" },
  { id: "66", name: "Ortigas Business District", name_en: "Ortigas Business District", name_zh: "Ortigas Business District", region: "Metro Manila", address: "Unit 0102B Hanston Ortigas 20 F Ortigas Jr Road Ortigas Center San Antonio City of Pasig NCR, Second District", phone: "(02)8922-2222" },
  { id: "67", name: "Avida Tower 2 BGC", name_en: "Avida Tower 2 BGC", name_zh: "Avida Tower 2 BGC", region: "Metro Manila", address: "Unit 07 & 08 G/F Avida Towers Cityflex Tower 2 7th Ave. Bonifacio Global City Taguig City NCR, Fourth District", phone: "(02)8922-2222" },
  { id: "68", name: "Doña Soledad Paranaque", name_en: "Doña Soledad Paranaque", name_zh: "Doña Soledad Paranaque", region: "Metro Manila", address: "Pilinas Shell Dona Soledad Avenue Better Living Subd Don Bosco City of Paranaque NCR, Fourth District", phone: "(02)8355-8125 | (02) 8922-2222" },
  { id: "69", name: "Camarin Caloocan", name_en: "Camarin Caloocan", name_zh: "Camarin Caloocan", region: "Metro Manila", address: "GF Unit ABC YAYA Hotel 1, Evangelista St Corner Zapote St Camarin Caloocan City", phone: "(02)-82839851" },
  { id: "70", name: "West Drive Marikina", name_en: "West Drive Marikina", name_zh: "West Drive Marikina", region: "Metro Manila", address: "West Drive Commercial Center l-2 B-37 of Marikina NCR, Second District", phone: "(02)8922-2222" },
  { id: "71", name: "Muntinlupa", name_en: "Muntinlupa", name_zh: "Muntinlupa", region: "Metro Manila", address: "Estanislao St., Cor. Genaro Lakeview Homes Putatan Muntinlupa City", phone: "0927-227-5758" },
  { id: "72", name: "Moriones St. Tondo", name_en: "Moriones St. Tondo", name_zh: "Moriones St. Tondo", region: "Metro Manila", address: "Marssha Tower, 1318 Franco St., Corner Moriones St., Tondo Manila", phone: "(02)8922-2222" },
  { id: "73", name: "Kabihasnan", name_en: "Kabihasnan", name_zh: "Kabihasnan", region: "Metro Manila", address: "Unit A Lot 1-A Quirino Avenue San Dionisio City of Paranaque NCR, Fourth District", phone: "" },
  { id: "74", name: "Aurora BLVD", name_en: "Aurora BLVD", name_zh: "Aurora BLVD", region: "Metro Manila", address: "Unit A UGF Aurum Place 935 Aurora Blvd. Silangan Quezon City NCR, Second DISTRICT", phone: "" },
  { id: "75", name: "Malabon", name_en: "Malabon", name_zh: "Malabon", region: "Metro Manila", address: "Ground Floor Quadricentennial Plaza San Bartolome Parish Compound Rizal Avenue Ext., San Agustin City of Malabon NCR, Third District", phone: "" },
  { id: "76", name: "Maypajo Caloocan", name_en: "Maypajo Caloocan", name_zh: "Maypajo Caloocan", region: "Metro Manila", address: "198 A. Mabini St Maypajo Barangay 30 City Of Caloocan NCR, Third DISTRICT", phone: "" },
  { id: "77", name: "Almanza", name_en: "Almanza", name_zh: "Almanza", region: "Metro Manila", address: "Ground Floor G1 Almanza Square Building 490 Alabang Zapote Road Almanza Uno City Of Las Pinas NCR, Fourth DISTRICT", phone: "" },
  { id: "78", name: "Binondo", name_en: "Binondo", name_zh: "Binondo", region: "Metro Manila", address: "Unit 1 Ground Floor Lim Yee Wan Co., INC. 475 Quintin Paredes Street Barangay 289 Zone 027 Binondo NCR, City of Manila, First District", phone: "" },
  { id: "79", name: "Sandoval", name_en: "Sandoval", name_zh: "Sandoval", region: "Metro Manila", address: "Ground Floor Asprec BLDG II Blk 4 Lot 21 And 23 Sandoval Avenue Pinagbuhatan City of Pasig NCR, Second District", phone: "" },
  { id: "80", name: "Newport Pasay", name_en: "Newport Pasay", name_zh: "Newport Pasay", region: "Metro Manila", address: "Unit A11-13 Ground floor, Savoy Hotel, Newport City, Brgy.183, Pasay City, NCR, 4th District", phone: "0954-443-4980 | 0954-443-4961 | 0954-443-4978" },
  { id: "81", name: "Timog", name_en: "Timog", name_zh: "Timog", region: "Metro Manila", address: "Units 105-108 48 Timog Avenue Laging Handa Quezon City NCR, Second District", phone: "" },
  { id: "82", name: "Mckinley", name_en: "Mckinley", name_zh: "Mckinley", region: "Metro Manila", address: "A104A 568 West Campus Fort Bonifacio City of Taguig NCR, Fourth District", phone: "8922-2222 | 0954-332-9536 | 0991-682-6817" },
  { id: "83", name: "V Mapa", name_en: "V Mapa", name_zh: "V Mapa", region: "Metro Manila", address: "Unit A-B LJS Logistics Center 2 #3331 Victorino Mapa St Cor 2ND St Barangay 599 Zone 059 Santa Mesa NCR, City of Manila", phone: "" },
  { id: "84", name: "Holy Spirit", name_en: "Holy Spirit", name_zh: "Holy Spirit", region: "Metro Manila", address: "Unit C Lower Ground Floor The Rock Building Lot 27 & 28 Blk. 4 Holy Spirit Drive Isidora Hills Subd. Holy Spirit Quezon City NCR, Second District", phone: "" },
  { id: "85", name: "Edsa Grand", name_en: "Edsa Grand", name_zh: "Edsa Grand", region: "Metro Manila", address: "UGF-13, Edsa Grand Residences EDSA, cor Corregidor, Bago Bantay, Quezon City, 1105 Metro Manila", phone: "0927-456-1748" },
  { id: "86", name: "CDO", name_en: "CDO", name_zh: "CDO", region: "Misamis Oriental", address: "Ground Floor Unit 4-6 Goking BLDG. Corrales Street Barangay 32 City of Cagayan De Oro Misamis Oriental", phone: "" },
  { id: "87", name: "Bacolod", name_en: "Bacolod", name_zh: "Bacolod", region: "Negros Occidental", address: "GF MICHAEL ANTONIO BLDG. LACSON ST. MANDALAGAN BACOLOD CITY CAPITAL NEGROS OCCIDENTAL", phone: "" },
  { id: "88", name: "Poblacion 6, Dumaguete", name_en: "Poblacion 6, Dumaguete", name_zh: "Poblacion 6, Dumaguete", region: "Negros Oriental", address: "53 SILLIMAN AVE. POBLACION NO. 6 BARANGAY 6 DUMAGUETE CITY CAPITAL NEGROS ORIENTAL", phone: "(35) 5275-270" },
  { id: "89", name: "San Jose Nueva Ecija", name_en: "San Jose Nueva Ecija", name_zh: "San Jose Nueva Ecija", region: "Nueva Ecija", address: "San Jose Nueva Ecija", phone: "" },
  { id: "90", name: "Calapan City", name_en: "Calapan City", name_zh: "Calapan City", region: "Oriental Mindoro", address: "Ground Floor Nuciti Central Mall, Brgy Camilmil Calapan City Oriental Mindorro", phone: "0995-504-0253 | 043-7485019" },
  { id: "91", name: "Angeles Pampanga", name_en: "Angeles Pampanga", name_zh: "Angeles Pampanga", region: "Pampanga", address: "Kira Kira Commercial Complex Rizal Ext. cor. Fil-Am Friendship Highway Brgy. Cutcut Angeles City, Pampanga", phone: "(045)4552222" },
  { id: "92", name: "San Fernando Pampanga", name_en: "San Fernando Pampanga", name_zh: "San Fernando Pampanga", region: "Pampanga", address: "Kingsborough Commercial Center Jose Abad Santos Ave. Dolores City of San Fernando Capital Pampanga", phone: "(045)455-2222" },
  { id: "93", name: "Sindalan", name_en: "Sindalan", name_zh: "Sindalan", region: "Pampanga", address: "Ground Floor Palm Building Mc Arthur Highway Sindalan City Of San Fernando Pampanga", phone: "" },
  { id: "94", name: "Dagupan", name_en: "Dagupan", name_zh: "Dagupan", region: "Pangasinan", address: "A.B. Fernandez Ave., Assada Center, Dagupan City", phone: "(075)529-1249 | (075)529-1207 | 0922-880-9523 | 0923-102-3989 | 0922-880-9515 | 0915-395-6497" },
  { id: "95", name: "Urdaneta Pangasinan", name_en: "Urdaneta Pangasinan", name_zh: "Urdaneta Pangasinan", region: "Pangasinan", address: "GFN 14B 15 & 16 CB MALL MC ARTHUR HIGHWAY NANCAYASAN CITY OF URDANETA PANGASINAN", phone: "" },
  { id: "96", name: "Lucao Dagupan", name_en: "Lucao Dagupan", name_zh: "Lucao Dagupan", region: "Pangasinan", address: "Dagupan-Binmaley Road Cor. J. De Venecia Road, Lucao District, Dagupan City, Pangasinan", phone: "" },
  { id: "97", name: "Ilayang Iyam, Lucena", name_en: "Ilayang Iyam, Lucena", name_zh: "Ilayang Iyam, Lucena", region: "Quezon Province", address: "Unit 1 & 2 Grantsy Building 4595 M.L. Tagararao Street Barangay 5 Pob. Lucena City Capital Quezon", phone: "" },
  { id: "98", name: "Candelaria", name_en: "Candelaria", name_zh: "Candelaria", region: "Quezon Province", address: "Cabunag St. Poblacion Candelaria Quezon", phone: "" },
  { id: "99", name: "Gems Plaza Antipolo", name_en: "Gems Plaza Antipolo", name_zh: "Gems Plaza Antipolo", region: "Rizal", address: "Unit F, Gems Bldg., Circumferential Rd., Brgy. Dalig, Antipolo City", phone: "" },
  { id: "100", name: "Cainta", name_en: "Cainta", name_zh: "Cainta", region: "Rizal", address: "1 L. SANTOS SAN JUAN CAINTA CAINTA RIZAL", phone: "(02)8722-3184" },
  { id: "101", name: "Taytay Rizal", name_en: "Taytay Rizal", name_zh: "Taytay Rizal", region: "Rizal", address: "MARC Square Commercial Building Rizal Ave. San Juan Taytay Rizal", phone: "8364-2965" },
  { id: "102", name: "San Mateo Rizal", name_en: "San Mateo Rizal", name_zh: "San Mateo Rizal", region: "Rizal", address: "Cedar Building Malanday San Mateo Rizal", phone: "" },
  { id: "103", name: "Primark Rodriguez", name_en: "Primark Rodriguez", name_zh: "Primark Rodriguez", region: "Rizal", address: "G04-B Primark Town Center Sto. Nino Masigla Market Kasiglahan Village San Jose Rodriguez Rizal", phone: "" },
  { id: "104", name: "Binangonan", name_en: "Binangonan", name_zh: "Binangonan", region: "Rizal", address: "Blk Lot 3 Manila East Road Blueridge Subd Tagpos Binangonan Rizal", phone: "" },
  { id: "105", name: "Tarlac", name_en: "Tarlac", name_zh: "Tarlac", region: "Tarlac", address: "G/F B2-E AND B2-F CITYWALK ZAMORA STREET SAN ROQUE CITY OF TARLAC CAPITAL TARLAC", phone: "(045)931-7487" },
  { id: "106", name: "Capas", name_en: "Capas", name_zh: "Capas", region: "Tarlac", address: "McArthur HWAY Santo Domingo 2ND Capas Tarlac", phone: "" },
  { id: "107", name: "Olongapo", name_en: "Olongapo", name_zh: "Olongapo", region: "Zambales", address: "395 Rizal Avenue West Tapinac City of Olongapo Zambales", phone: "" },
  { id: "108", name: "Pagadian", name_en: "Pagadian", name_zh: "Pagadian", region: "Zamboanga Del Sur", address: "Ground Floor Luy Building J.P. Rizal Avenue Santa Lucia City of Pagadian Zamboanga Del Sur", phone: "" },
]

export type AngelPizzaStore = (typeof ANGEL_PIZZA_STORES)[number]

/** Prefix for order sheets / lists: Angel's Pizza branch (not a URL; display label). */
export const ANGEL_PIZZA_STORE_ORDER_PREFIX = 'angelspizza'

/** e.g. `angelspizza-Butuan` */
export function formatAngelPizzaStoreLabel(store: Pick<AngelPizzaStore, 'id' | 'name' | 'name_en' | 'name_zh'>): string {
  const branch = (store.name_en || store.name_zh || store.name).trim()
  return `${ANGEL_PIZZA_STORE_ORDER_PREFIX}-${branch}`
}

/** e.g. `angelspizza-Butuan (1)` — branch + internal store id */
export function formatAngelPizzaStoreLine(store: Pick<AngelPizzaStore, 'id' | 'name' | 'name_en' | 'name_zh'>): string {
  return `${formatAngelPizzaStoreLabel(store)} (${store.id})`
}
